controller_list:
  - name: move_aidana
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - motortom2m
      - joint2
      - joint4
      - joint6
      - end


